services:
  db:
    image: mysql
    container_name: mysql_containercont
    ports:
      - "6033:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_DATABASE=exo_dock
    volumes:
      - mysql_volume:/var/lib/mysql



  frontadmin:
    image: phpmyadmin
    container_name: phpadmin_cont
    restart: always
    ports:
      - "8910:80"
    environment:
      - PMA_HOST=db

    depends_on:
      - db



  app:
    build:
      context: .
   # image: openjdk
    container_name: ${MY_PROJECT_NAME}
    restart: always






volumes:
  mysql_volume: